### ISSUE TITLE
Remove dependency to Blender

### ISSUE THREAD

**Issue by ghost** [antfarmar/Unity-3D-Asteroids#12]
I forked your project to have a look and possibly provide some comments for you to meditate on. However, I am unable to play the game because it requires Blender. This means there are no meshes for rendering and no meshes for collision. 

It would be really, really nice if you exported your .blend files as .fbx files instead, because that doesn't require Blender to be installed on the machine. As an interesting side note, Unity Cloud Build also doesn't support .blend files so it could be something keeping in mind.

Upon starting Unity, I get this error three times:

```
Blender could not be found.
Make sure that Blender is installed and the .blend file has Blender as its 'Open with' application!
```
- [ ] asteroid1_model
- [ ] asteroid2_model
- [ ] ship_model

**Comment by antfarmar** [comment]
Hey there. Nice to see somebody following the project!

As for the issue you mention:
Exporting to .fbx was how I originally added the model assets, but later found out Unity could do it automatically, so I just saved the .blend file to the folder instead of just exporting the fbx file for convenience. I will change this asap.

While the manual mentions:

> This works under the hood by using the Blender FBX exporter

I took it to mean they implemented Blender's FBX exporting source into Unity. I didn't know that Unity actually requires and executes Blender. Interesting.

See:
http://docs.unity3d.com/Manual/HOWTO-ImportObjectBlender.html

**Comment by antfarmar** [comment]
Dependency removed:

Added seperate .fbx model exports to Assets\Models\FBX.
- Note: Each model's Import Settings Scale Factor is set to 100 to have correct scale.

Blender .blend files moved to Assets\Models\Blender.

**_The .fbx models are now the default models used/referenced in each prefab's `MeshFilter` component, as well as their respective `MeshCollider`.**_

**Comment by ghost** [comment]
> I didn't know that Unity actually requires and executes Blender. Interesting.

Yeah, there's some things you won't expect at first glance.

[Art Asset Best Practice Guide](http://docs.unity3d.com/Manual/HOWTO-ArtAssetBestPracticeGuide.html)

> #### Import/Export
> 
> Unity can use two types of files: Saved 3D application files and Exported 3D formats. Which you decide to use can be quite important:
> ...
> 
> ###### Disadvantages:
> - A **licensed copy of that software must be installed on all machines** using the Unity project
