### ISSUE TITLE
Teamwork communication channel

### ISSUE THREAD

**Issue by ghost** [antfarmar/Unity-3D-Asteroids#19]
So, I admit; I am pretty new to github. 

It has great social features, but it appear to lack (or I have not found so) a place to discuss general topics or planning.

Could you please look into options for us to communicate a little bit if you want to team up?
- [x] Built in discussion board in Github?
- [x] Github plugins? (I seen there are lots, tried none)
- [ ] Forum
- [ ] IRC
- [ ] Other chat networks
- [ ] Email

Perhaps any of the above could work. Try to pick one with least amount of hassle. 
It shouldn't be a chore to talk.

**Comment by antfarmar** [comment]
OK I will look into this, since your avatar reminds me of notch aka Markus Persson, and I too hope to one day be able to outbid Jay-Z & Beyonce on a Beverly Hill mansion :laughing:. I hope you're as lucky and as good a developer as him.

All joking aside, I'm new to GitHub as well. But my initial thought is to **keep all discussions here on GitHub, so that everything remains central and localized.**

Perhaps we could simply use the Issues system for discussions, and/or even the Wiki?
- The Issues system has custom tags and filters, and we seem to currently be doing OK with it.
- We could create a Wiki page per topic discussed as well.
- Chat is another issue. (https://gitter.im/)

This way all our thoughts and work remain easily accessible to us and others that may be interested.
An external chat site I've seen others use is https://gitter.im/ which is free and popular. I guess it all depends on where this is going.

Now all we need is something cool and interesting to create and collaborate on! :metal:

**Comment by ghost** [comment]
I just got moved in and got internet access the last few moments. I'll catch up on things tomorrow.

Don't get alarmed from my diverge branch on my fork - I am not expecting to merge stuff in. I am just experimenting a little bit. Gotta rush.

**Comment by antfarmar** [comment]
Cool. I hope everything went well with your move.
And yeah, our projects are probably very different by now. No worries.
Cheers.

**Comment by ghost** [comment]
I'm settled in now and it's not late at night :+1: 

Let's give issues a spin first to see if it's simple or if it gets confusing.
If we run into workflow issues, let's consider using the wiki or gitter. 
I did register with gitter, so if you know how to invite me to your gitter room, feel free to send an invite.

I sent you an invite to my fork, just to learn how it works. Feel free to accept the invite and leave after a day or so - I just want to see what kind of stuff is accessible from the owners point of view.

Btw, what timezone are you active in? I'm usually free 1 PM - 1 AM Central European Time. Chat for real-time purposes will be difficult if we aren't overlapping in time. It can still be useful as a kind of "public mailing list" if the messages persist, although feels a little bit like the wrong tool for the job :)

**Comment by antfarmar** [comment]
I'm EST, so 1PM-1AM CET would be 7AM-7PM EST.

That's sounds OK for me.
I haven't used gitter yet. I'll check it out though.
